### ISSUE TITLE
Bug in Edit Placement.

### ISSUE THREAD

**Issue by Abhinav-ark** [Ashrockzzz2003/placement_tracker_web#2]
While adding company in Edit Placement, Request to edit placement is submitted automatically, which closes the edit placement window.

**Comment by eshwanthkartitr** [comment]
Hi @Abhinav-ark I would like to work on this issue

**Comment by Ashrockzzz2003** [comment]
Hi @eshwanthkartitr 
You have time until Thursday `26/12/2024` to work on this and come up with a PR. Assigned this to you.

**Comment by SHRIMONESH** [comment]
iam also interested in this issue if there is no progress iam willing to take this issue

**Comment by adithya-menon-r** [comment]
Hey @Ashrockzzz2003, I would like to solve this issue if there is no progress.

**Comment by Ashrockzzz2003** [comment]
HI @adithya-menon-r and @SHRIMONESH 

The previously assigned person has raised a PR for the same.
This issue is not available rn.

But you can find bugs in code, behavior and create your own issues and tag us. It'll be assigned to you if its valid.
